cart/urls.py
from django.conf.urls import include, url

from cart.views import CartView, delete_item

urlpatterns = [
   url(r'^$', CartView.as_view(), name='user_cart'),
   url(r'^delete/$', delete_item, name='delete_user_cart'),

]

e_store/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

from e_store import settings
from django.conf.urls.static import static

urlpatterns = [
                  url(r'^$', include('products.urls')),
                  url(r'^ckeditor/', include('ckeditor_uploader.urls')),
                  url(r'^admin_sunny/', admin.site.urls),
                  url(r'^user/', include('user_management.urls')),
                  url(r'^accounts/', include('allauth.urls')),
                  url(r'^products/', include('products.urls')),
                  url(r'^cart/', include('cart.urls')),
                  url(r'^order/', include('order.urls')),
                  url(r'^contact-us/', TemplateView.as_view(template_name='global/contact.html'), name='contact_us'),
                  url(r'^tutorial/', TemplateView.as_view(template_name='global/tutorial.html'), name='tutorial'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ... your normal urlpatterns here

products/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from products.views import ProductDetails, CommentView, add_to_cart, ProductsView, search_products

urlpatterns = [
   url(r'^$', ProductsView.as_view(), name='products_list'),
   url(r'^detail/(?P<pk>\d+)/$', ProductDetails.as_view(), name='product_detail'),
   url(r'^detail/(?P<product_pk>\d+)/comments/$', CommentView.as_view(), name='product_comments'),
   url(r'^detail/(?P<product_pk>\d+)/add_to_cart/$', add_to_cart, name='add_to_cart'),
   url(r'^search-products/$', search_products, name='search_products'),
]

products/models.py
from __future__ import unicode_literals

from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Category(models.Model):
    name = models.CharField(max_length=64, null=True, blank=True)

    class Meta:
        verbose_name = '产品类别'
        verbose_name_plural = '产品类别'

    def __str__(self):
        return self.name


class Notification(models.Model):
    description = models.TextField()

class Brand(models.Model):
    name = models.CharField(max_length=64, null=True, blank=True)

    class Meta:
        verbose_name = '产品品牌'
        verbose_name_plural = '产品品牌'

    def __str__(self):
        return self.name


class Product(models.Model):
    PRODUCT_STATUS = (
        ('New', '新品'),
        ('Sales', '折扣'),
    )
    name = models.CharField(max_length=128)
    description = RichTextUploadingField(null=True, blank=True)
    price = models.FloatField()
    brand = models.ForeignKey(Brand, null=True, blank=True)
    stars = models.IntegerField(default=5, null=True, blank=True)
    categories = models.ManyToManyField(Category, null=True, blank=True)
    status = models.CharField(choices=PRODUCT_STATUS, null=True, blank=True, max_length=64)
    weight = models.FloatField(null=True, blank=True)
    unit = models.IntegerField(null=True, blank=True)
    post_fee_included = models.BooleanField(default=False)

    class Meta:
        verbose_name = '我的产品'
        verbose_name_plural = '我的产品'


    def __str__(self):
        return self.name


class ProductReview(models.Model):
    content = models.TextField()
    stars = models.FloatField(null=True, blank=True, default=5)
    user = models.ForeignKey(User, blank=True, null=True)
    product = models.ForeignKey('Product', blank=True, null=True)
    created_time = models.DateTimeField(default=timezone.now())

    class Meta:
        verbose_name = '产品评价'
        verbose_name_plural = '产品评价'


class ProductImages(models.Model):
    product = models.ForeignKey('Product', related_name='images')
    image = models.ImageField()

    class Meta:
        verbose_name = '产品图片'
        verbose_name_plural = '产品图片'


    def __str__(self):
        return self.product.name


class ProductImageInline(admin.TabularInline):
    model = ProductImages


class ProductAdmin(admin.ModelAdmin):
    inlines = [
        ProductImageInline,
    ]


class UserProduct(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    product = models.ForeignKey(Product, null=True, blank=True)
    quantity = models.IntegerField(default=0)
    created_time = models.DateTimeField(null=True, blank=True, default=timezone.now())
    type = models.IntegerField(null=True, blank=True)

    class Meta:
        verbose_name = '购物车管理'
        verbose_name_plural = '购物车管理'
    # 0. in cart
    # 1. submitted
    # 2. processed
    # 3. whishlist

products/forms.py
from django import forms
from django.forms import TextInput, Textarea
from products.models import ProductReview, UserProduct

class CommentForm(forms.ModelForm):

    class Meta:
        model = ProductReview
        widgets = {
             'stars': forms.HiddenInput()
        }
        fields = ['content', 'stars']


class CartForm (forms.ModelForm):
    class Meta:
        model = UserProduct
        widgets = {
            'quantity': forms.TextInput(attrs={'min': 1, 'step':1})
        }
        fields = ['quantity']

products/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.template import RequestContext
from django.views.generic import DetailView, CreateView, ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from products.models import Product, ProductReview, UserProduct, Category, Brand, Notification
from products.forms import CommentForm, CartForm


class ProductsView(ListView):
    model = Product
    paginate_by = 30
    context_object_name = 'products'
    template_name = 'products/list.html'

    def get_context_data(self, **kwargs):
        context = super(ProductsView, self).get_context_data(**kwargs)
        context['notification'] = Notification.objects.all()
        context['categories'] = Category.objects.all()
        context['brands'] = Brand.objects.all()
        context['discounts'] = Product.objects.filter(status='Sales')
        if 'brand' in self.request.GET or 'category' in self.request.GET:
            context['search_result'] = True
        return context

    def get_queryset(self):
        if 'brand' in self.request.GET:
            return Product.objects.filter(brand_id=self.request.GET['brand'])
        elif 'category' in self.request.GET:
            return Product.objects.filter(categories__id__in=[self.request.GET['category']])
        else:
            return Product.objects.all()


class ProductDetails(DetailView):
    model = Product
    template_name = 'products/detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super(ProductDetails, self).get_context_data(**kwargs)
        context['cart_form'] = CartForm()
        return context


class CommentView(CreateView):
    model = ProductReview
    form_class = CommentForm
    template_name = 'products/comment.html'

    def get_context_data(self, **kwargs):
        context = super(CommentView, self).get_context_data(**kwargs)
        context['comments'] = ProductReview.objects.filter(product__pk=self.kwargs['product_pk'])
        context['product'] = Product.objects.get(pk=self.kwargs['product_pk'])
        context['user'] = self.request.user
        return context

    def form_invalid(self, form):
        return redirect('product_detail', pk=self.kwargs['product_pk'])

    def form_valid(self, form):
        if not self.request.user or not self.request.user.is_authenticated:
            return redirect('account_login')

        comment = ProductReview()
        comment.content = form.cleaned_data['content']
        comment.stars = form.cleaned_data['stars']
        comment.product_id = self.kwargs['product_pk']
        comment.user_id = self.request.user.id
        comment.save()
        return redirect('product_detail', pk=self.kwargs['product_pk'])


@login_required(login_url='account_login')
def add_to_cart(request, *args, **kwargs):
    if request.method == 'POST':
        form = CartForm(request.POST)
        if form.is_valid():
            cart_queryset = UserProduct.objects.filter(product_id=kwargs['product_pk'], user_id=request.user.id, type=0)
            if cart_queryset.__len__() >= 1:
                cart = cart_queryset.first()
                cart.quantity = cart.quantity + form.cleaned_data['quantity']
                cart.save()
            else:
                cart = UserProduct()
                cart.quantity = form.cleaned_data['quantity']
                cart.product_id = kwargs['product_pk']
                cart.user_id = request.user.id
                cart.type = 0
                cart.save()

            context = RequestContext(request)
            context['add_success'] = True
            context['cart_form'] = CartForm()
            return JsonResponse({'status': 200})


def search_products(request, *args, **kwargs):
    if request.method == 'POST':
        context = {}
        context['categories'] = Category.objects.all()
        context['brands'] = Brand.objects.all()
        context['search_result'] = True
        context['products'] = Product.objects.filter(name__icontains=request.POST['search_params'])[:10]
        return render(request, 'products/list.html', context=context, status=200)

products/templates/products/_product_list.html

<div class="features_items"><!--features_items-->
    {% for product in products %}
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <div class="productinfo text-center">
                        <img src="{{ product.images.all.0.image.url }}" alt="" />
                        <h2>{{ product.price }}元</h2>
                        <p>{{ product.name }}</p>
                        <a href="{% url 'product_detail' product.pk %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>查看详情</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div><!--features_items-->

products/templates/products/comment.html
<div class="category-tab shop-details-tab"><!--category-tab-->
    <div class="col-sm-12">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#reviews" data-toggle="tab">顾客评价 ({{ comments.count }})</a></li>
        </ul>
    </div>
    <div class="tab-content">
        <div class="tab-pane fade active in" id="reviews" >
            <div class="col-sm-12">
                {% for comment in comments %}
                    <ul>
                        <li><a href=""><i class="fa fa-user"></i>{{ comment.user.username }}</a></li>
                        <li><a href=""><i class="fa fa-clock-o"></i>{{ comment.created_time|date:'H:i' }}</a></li>
                        <li><a href=""><i class="fa fa-calendar-o"></i>{{ comment.created_time|date:'Y-m-d' }}</a></li>
                        <li><a href=""><i class="fa fa-star"></i>{{ comment.stars }}</a></li>
                    </ul>

                    <p>{{ comment.content }}</p>
                {% endfor %}
                {% if user.is_authenticated %}
                <p><b>评价宝贝</b></p>
                <form id="comment-form" action="{% url 'product_comments' product.id %}" method="post">
                    {% csrf_token %}
                    {{ form.content }}
                    {{ form.content.errors }}
                    {{ form.stars }}
                    {{ form.stars.errors }}
                    <div class="row">
                        <b> 评分: </b>
                    </div>
                    <fieldset class="rating">
                        <input type="radio" id="star5" name="rating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
                        <input type="radio" id="star4half" name="rating" value="4.5" /><label class="half" for="star4half" title="Pretty good - 4.5 stars"></label>
                        <input type="radio" id="star4" name="rating" value="4" /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
                        <input type="radio" id="star3half" name="rating" value="3.5" /><label class="half" for="star3half" title="Meh - 3.5 stars"></label>
                        <input type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="Meh - 3 stars"></label>
                        <input type="radio" id="star2half" name="rating" value="2.5" /><label class="half" for="star2half" title="Kinda bad - 2.5 stars"></label>
                        <input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="Kinda bad - 2 stars"></label>
                        <input type="radio" id="star1half" name="rating" value="1.5" /><label class="half" for="star1half" title="Meh - 1.5 stars"></label>
                        <input type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="Sucks big time - 1 star"></label>
                        <input type="radio" id="starhalf" name="rating" value="half" /><label class="half" for="starhalf" title="Sucks big time - 0.5 stars"></label>
                    </fieldset>

                    <button type="submit" class="btn btn-default pull-right">
                        提交评论
                    </button>
                    <p class="message"></p>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $("input[type='radio']").click(function () {
            $('#{{ form.stars.auto_id }}').val($(this).val());
        });
        {% if user.is_authenticated %}
        $('#{{ form.user_id.auto_id }}').val({{ user.id }});
        {% endif %}
        $('#{{ form.product_id.auto_id }}').val({{ product.id }});
    });
</script>

products/templates/products/detail.html
{% extends 'base.html' %}
{% load static %}
{% block slider %}{% endblock %}
{% block sidebar %}{% endblock %}
{% block content %}

    <style>
        .owl-carousel {
            position: relative;
        }
        .owl-prev,
        .owl-next {
            background: #FE980F !important;
            position: absolute;
            top: 50%;
            margin-top: -10px; // Half of the prev/next buttons height here in negatives to center them perfectly
        }
        .owl-prev {
            left: 0;
        }
        .owl-next {
            right: 0;
        }
        .owl-dot.active > span {
            background: #FE980F !important;
        }


        fieldset, label { margin: 0; padding: 0; }
        body{ margin: 20px; }
        h1 { font-size: 1.5em; margin: 10px; }

        /****** Style Star Rating Widget *****/

        .rating {
            border: none;
            float: left;
        }

        .rating > input { display: none; }
        .rating > label:before {
            margin: 5px;
            font-size: 1.25em;
            font-family: FontAwesome;
            display: inline-block;
            content: "\f005";
        }

        .rating > .half:before {
            content: "\f089";
            position: absolute;
        }

        .rating > label {
            color: #ddd;
            float: right;
        }

        /***** CSS Magic to Highlight Stars on Hover *****/

        .rating > input:checked ~ label, /* show gold star when clicked */
        .rating:not(:checked) > label:hover, /* hover current star */
        .rating:not(:checked) > label:hover ~ label { color: #FFD700;  } /* hover previous stars in list */

        .rating > input:checked + label:hover, /* hover current star when changing rating */
        .rating > input:checked ~ label:hover,
        .rating > label:hover ~ input:checked ~ label, /* lighten current selection */
        .rating > input:checked ~ label:hover ~ label { color: #FFED85;  }

    </style>
    <div class="row product-details"><!--product-details-->
        <div class="col-sm-5">
            <div class="owl-carousel owl-theme">
                {% for img in product.images.all %}
                    <div class="view-product">
                        <div class="view-product">
                            <img style="object-fit: contain;" src="{{ img.image.url }}" alt="" />
                        </div>
                    </div>
                {% endfor %}
            </div>

            <div id="comment-box">

            </div>
        </div>
        <div class="col-sm-7">
            <div class="product-information"><!--/product-information-->
                {% ifequal product.status 'Sales' %}
                    <img src="{% static 'global/images/product-details/new.jpg'%}" class="newarrival" alt="" />
                {% endifequal %}
                <h2>{{ product.name }}</h2>
                <form id="cart-form" action="{% url 'add_to_cart' product.id %}" method="post">
                    <span>
                        <span>{{ product.price }}元</span>

                        {% csrf_token %}
                        {{ cart_form.quantity }}
                        <button type="submit" class="btn btn-fefault cart">
                            <i class="fa fa-shopping-cart"></i>
                            添加到购物车
                        </button>
                    </span>
                </form>
                <p>产品详情</p>
                <br>
                <div id="product-description">
                    {{ product.description | safe }}
                </div>
            </div><!--/product-information-->
        </div>
    </div><!--/product-details-->
{% endblock %}
{% block javascript %}
    <script>
        $(document).ready(function() {
            $(".owl-carousel").owlCarousel({
                items:1,
                loop:true,
                autoplay: true,
                autoPlaySpeed: 3000,
                autoplayHoverPause: true,
                nav:true,
                navText: ["<i class='fa fa-angle-left'>","<i class='fa fa-angle-right'>"]
            });

            // Init comment box;
            $.get('{% url 'product_comments' product.pk %}', function(html) {
                $('#comment-box').html(html);
            });

            $('#cart-form').submit(function(event) {
                event.preventDefault(); //this will prevent the default submit
                if($('#id_quantity').val() <=0) {
                    swal("添加购物车失败", "添加数量必须大于0.", "warning")
                } else {
                    $.ajax({
                        type: "POST",
                        url: "{% url 'add_to_cart' product.pk %}",
                        data: $(this).serialize(), // serializes the form's elements.
                        success: function(data)
                        {
                            if(data.status && data.status == 200) {
                                {#                                swal("{{ product.name }}", "你已成功添加至购物车", "success")#}
                                swal({
                                        title: "已成功添加至购物车",
                                        text: "现在提交订单吗？",
                                        type: "success",
                                        showCancelButton: true,
{#                                        confirmButtonColor: "#DD6B55",#}
                                        confirmButtonText: "是的，前往购物车",
                                        cancelButtonText: "等等, 我要继续购物",
                                        closeOnConfirm: false
                                    },
                                    function(){
                                        location.href = '{% url 'user_cart' %}'
                                    });
                            } else {
                                swal("添加购物车失败", "请确认已经登录系统", "warning")
                            }

                        }
                    });
                }
            });

            $("#product-description img").css("width", "100%");
            $("#product-description img").css("height", "auto");
        });

        $(function () {
            $('.share-bar').share({
                sites: ['qzone', 'qq', 'weibo','wechat']
            });
        });
    </script>
{% endblock %}

products/templates/products/list.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

    {#    <section id="slider"><!--slider-->#}
    {#        <div class="container">#}
    {#            <div class="row">#}
    {#                <div class="col-sm-12">#}
    {#                    <div id="slider-carousel" class="carousel slide" data-ride="carousel">#}
    {#                        <ol class="carousel-indicators">#}
    {#                            <li data-target="#slider-carousel" data-slide-to="0" class="active"></li>#}
    {#                            <li data-target="#slider-carousel" data-slide-to="1"></li>#}
    {#                            <li data-target="#slider-carousel" data-slide-to="2"></li>#}
    {#                        </ol>#}
    {##}
    {#                        <div class="carousel-inner">#}
    {#                            <div class="item active">#}
    {#                                <div class="col-sm-6">#}
    {#                                    <h1><span>Hi mate，</span>Welcome！</h1>#}
    {#                                    <h2>全球顶级品质保障</h2>#}
    {#                                    <p>澳洲的质量检测是全球闻名，墨尔本更是多年被评为全球最宜居城市。这样的环境使得澳洲本地食品从土壤和空气里就已经是其他国家无法相比的了，食品安全的确做的非常好。Product in Australia就意味着品质的保证。 </p>#}
    {#                                    <button type="button" class="btn btn-default get">Get it now</button>#}
    {#                                </div>#}
    {#                                <div class="col-sm-6">#}
    {#                                    <img src="{% static 'global/images/home/girl1.jpg' %}" class="girl img-responsive" alt="" />#}
    {#                                </div>#}
    {#                            </div>#}
    {#                            <div class="item">#}
    {#                                <div class="col-sm-6">#}
    {#                                    <h1><span>国际直邮</span> 澳洲产品</h1>#}
    {#                                    <h2>100% 源自澳大利亚</h2>#}
    {#                                    <p>澳大利亚具有优越的自然环境，是世界上空气污染最少的地区之一，而且澳洲还有着近乎苛刻的药检标准及保健品管理制度，故其出产的健康食品早己享誉全球。澳大利亚保健品原料选择极其严格，使用理代化检验方法检测原料的含量和毒性（农药残留、重金属、致病菌等），原料多为纯天然、无污染、活性含量充足</p>#}
    {#                                    <button type="button" class="btn btn-default get">Get it now</button>#}
    {#                                </div>#}
    {#                                <div class="col-sm-6">#}
    {#                                    <img src="{% static 'global/images/home/girl2.jpg' %}" class="girl img-responsive" alt="" />#}
    {#                                </div>#}
    {#                            </div>#}
    {##}
    {#                            <div class="item">#}
    {#                                <div class="col-sm-6">#}
    {#                                    <h1><span>WELCOME</span> TO MELBOURNE</h1>#}
    {#                                    <h2>Best Product & Competitive Rate </h2>#}
    {#                                    <p>亲，你好。我长期居住在澳洲。有任何需要在澳洲代购的产品都可以告诉我。我会以最快的速度和最优惠的价格帮你买到！全部直邮到中国。谢谢!</p>#}
    {#                                    <button type="button" class="btn btn-default get">Get it now</button>#}
    {#                                </div>#}
    {#                                <div class="col-sm-6">#}
    {#                                    <img src="{% static 'global/images/home/girl3.jpg' %}" class="girl img-responsive" alt="" />#}
    {#                                </div>#}
    {#                            </div>#}
    {##}
    {#                        </div>#}
    {##}
    {#                        <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">#}
    {#                            <i class="fa fa-angle-left"></i>#}
    {#                        </a>#}
    {#                        <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">#}
    {#                            <i class="fa fa-angle-right"></i>#}
    {#                        </a>#}
    {#                    </div>#}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {#    </section><!--/slider-->#}


    <section>
        <div class="container">
            <div class="row">
                {% block sidebar %}
                    <div class="col-sm-3">
                        <div class="left-sidebar">
                            <h2>商品分类</h2>
                            <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                                {% for category in categories %}
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">
                                                <a href="{% url 'products_list' %}?category={{ category.pk }}">
                                                    {{ category.name }}
                                                </a>
                                            </h4>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div><!--/category-products-->

                            <div class="brands_products"><!--brands_products-->
                                <h2>澳洲品牌</h2>
                                <div class="brands-name">
                                    <ul class="nav nav-pills nav-stacked">
                                        {% for brand in brands %}
                                            <li><a href="{% url 'products_list' %}?brand={{ brand.pk }}">{{ brand.name }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div><!--/brands_products-->


                            {#						<div class="shipping text-center"><!--shipping-->#}
                            {#							<img src="{% static 'images/home/shipping.jpg' %}" alt="" />#}
                            {#						</div><!--/shipping-->#}

                        </div>
                    </div>
                {% endblock %}

                {% if not search_result %}
                    {% block content %}
                        {% if discounts %}
                            <div class="col-sm-9 padding-right"><h2 class="title text-center">折扣商品</h2></div>
                            <div class="col-sm-9 padding-right">
                                {% include 'products/_product_list.html' with products=discounts %}
                            </div>

                            <div class="col-sm-offset-3 col-sm-9 padding-right"><h2 class="title text-center">所有商品</h2></div>
                            <div class="col-sm-offset-3 col-sm-9 padding-right">
                                {% include 'products/_product_list.html' with products=products %}
                            </div>
                            {% if page_obj.has_previous %}
                                <h4 class="pull-left"><a  style="color: #FE980F" href="?page={{ page_obj.previous_page_number}}"><上一页</a></h4>
                            {% endif %}

                            {% if page_obj.has_next %}
                                <h4 class="pull-right"><a   style="color: #FE980F"href="?&page={{ page_obj.next_page_number }}">下一页 ></a></h4>
                            {% endif %}

                        {% else %}
                            <div class="col-sm-9 padding-right"><h2 class="title text-center">所有商品</h2></div>
                            <div class="col-sm-9 padding-right">
                                {% include 'products/_product_list.html' with products=products %}
                            </div>
                            {% if page_obj.has_previous %}
                                <h4 class="pull-left"><a  style="color: #FE980F" href="?page={{ page_obj.previous_page_number}}"><上一页</a></h4>
                            {% endif %}

                            {% if page_obj.has_next %}
                                <h4 class="pull-right"><a   style="color: #FE980F"href="?&page={{ page_obj.next_page_number }}">下一页 ></a></h4>
                            {% endif %}
                        {% endif %}

                    {% endblock %}
                {% else %}
                    <div id="result-section" class="col-sm-9 padding-right"><h2 class="title text-center">搜索结果</h2></div>
                    <div class="col-sm-9 padding-right">
                        {% include 'products/_product_list.html' with products=products %}
                    </div>
                    {% if page_obj.has_previous %}
                        <h4 class="pull-left"><a  style="color: #FE980F" href="?page={{ page_obj.previous_page_number}}"><上一页</a></h4>
                    {% endif %}

                    {% if page_obj.has_next %}
                        <h4 class="pull-right"><a   style="color: #FE980F"href="?&page={{ page_obj.next_page_number }}">下一页 ></a></h4>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}

{% block javascript %}
    <script>
        {% if search_result %}
            $(document).ready(function() {
                $('html, body').animate({
                    scrollTop: $("#result-section").offset().top
                }, 1000);
            });
        {% endif %}
    </script>
{% endblock %}